# CICD Build Pipeline
# https://docs.microsoft.com/en-us/azure/devops/pipelines/?view=azure-devops
# https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema
# https://docs.microsoft.com/azure/devops/pipelines/languages/python
#
# Remote Execution
# 1 Run pipeline in Azure DevOps with remote_agent option selected
#
# Local Execution
# 1 Open PowerShell
# 2 Start the local Azure DevOps agent if previously configured (if not see Contributing.md > CICD Build Pipelines > Local Azure DevOps)
# 2a cd azure-local-pipeline; .\run.cmd;
# 3 Run pipeline in Azure DevOps with remote_agent option deselected
#
# See Also
# --------
#  Contributing.md > CICD Build Pipelines

parameters:
- name: remote_agent
  displayName: Remote Agent (Unselect to Run Local)
  type: boolean
  default: True

jobs:

  # run using Azure DevOps provided virtual machine
  - job: remote
    condition: eq(${{ parameters.remote_agent }}, True)
    displayName: 'pipeline using remote agent'
    # use Windows image for SQL Server Express to be included
    pool:
      vmImage: 'windows-latest'
    steps:
      - task: PowerShell@2
        displayName: 'Start SQL Server Express LocalDB'
        inputs:
          targetType: 'inline'
          script: 'sqllocaldb start mssqllocaldb'
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '$3.9'
        displayName: 'Use Python 3.9'
      - script: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
        displayName: 'Install Dependancies'
      # execute cicd.py script
      - task: PythonScript@0
        inputs:
          scriptSource: filePath
          scriptPath: cicd.py
          arguments: --server=(localdb)\\MSSQLLocalDB

  # run locally on laptop (requires Python and SQL Server Express to be installed)
  - job: local
    condition: eq(${{ parameters.remote_agent }}, False)
    displayName: 'pipeline using local agent'
    # local agent set up as described in Contributing.md
    pool: 'Local Laptop'
    steps:
      # deactivate any environment if activate, then create and activate a new environment        
      # - task: PowerShell@2
      #   displayName: 'Create Environment'
      #   inputs:
      #     targetType: 'inline'
      #     script: 
      #       try {deactivate} catch [Management.Automation.CommandNotFoundException] {};
      #       python -m venv env;
      #       .\env\Scripts\Activate.ps1;
      # create Python virtualenv and install requirements
      - task: PowerShell@2
        displayName: 'Create Environment & Install Dependancies'
        inputs:
          targetType: 'inline'
          script:
            python -m venv env;
            .\env\Scripts\Activate.ps1;
            python -m pip install --upgrade pip;
            pip install -r requirements-dev.txt;
            pip install -e.;
      # TODO: install package in editable mode if needed (pip install -e .)
      # run the CICD script that contains tests, coverage, etc.
      # TODO: execute Python script using the environment Python
      - task: PythonScript@0
        inputs:
          scriptSource: filePath
          scriptPath: cicd.py
          arguments: --server=localhost\SQLEXPRESS
          # workingDirectory: $(Build.SourcesDirectory)\env\Scripts\
          pythonInterpreter: $(Build.SourcesDirectory)\env\Scripts\python.exe
      # # deactivate then delete the created environment
      # - task: PowerShell@2
      #   displayName: 'Delete Environment'
      #   inputs:
      #     targetType: 'inline'
      #     script: 
      #       Remove-Item .\env -Recurse -Force;
