# CICD Build Pipeline
# https://docs.microsoft.com/en-us/azure/devops/pipelines/?view=azure-devops
# https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema
# https://docs.microsoft.com/azure/devops/pipelines/languages/python
#
# See also: Contributing.md > CICD Build Pipelines

parameters:
- name: remote_agent
  displayName: Remote Agent (Unselect to Run Local)
  type: boolean
  default: True

jobs:

  # run using Azure DevOps provided virtual machine
  - job: remote
    condition: eq(${{ parameters.remote_agent }}, True)
    displayName: 'pipeline using remote agent'
    pool:
      # Windows image for SQL Server Express to be included
      vmImage: 'windows-latest'
    steps:
      - script: echo running pipeline using remote agent
      - task: PowerShell@2
        displayName: 'start SQL Server Express LocalDB'
        inputs:
          targetType: 'inline'
          script: 'sqllocaldb start mssqllocaldb'
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '$3.9'
        displayName: 'Use Python 3.9'
      - script: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
        displayName: 'Install development and build dependancies'
      # - script: |
      #     pip installpytest-azurepipelines
      #   displayName: 'pytest'

  # run locally on laptop
  - job: local
    condition: eq(${{ parameters.remote_agent }}, False)
    displayName: 'pipeline using local agent'
    # local agent set up as described in Contributing.md
    pool: 'Local Laptop'
    steps:
      - script: echo running pipeline using local agent
      - script: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
        displayName: 'Install development and build dependancies'

# trigger:
# - main

# # windows image for SQL Server Express to be included
# pool:
#   vmImage: windows-latest

# execute cicd.py script
# - task: PythonScript@0
#   inputs:
#     scriptSource: filePath
#     script: cicd.py
#     arguments: --server=(localdb)\\MSSQLLocalDB