# Azure Pipelines Continuous Integration
#
# See Also
# --------
# CONTRIBUTING.md CICD Build Pipelines for a general overview of the CICD process
# cicd_template.yml for the core of the continuous integration process
# cicd_template.py for the core of the entire CICD process

pool: 
      vmImage: windows-latest

stages:

  - stage: ContinuousIntegration
    jobs:
      - job: ContinuousIntegration
        steps:
          - template: cicd_template.yml