# Azure Pipelines Continuous Deployment
#
# See Also
# --------
# CONTRIBUTING.md CICD Build Pipelines for a general overview of the CICD process
# continuous_integration.yml for the CI process
# cicd_template.py for the core of the entire CICD process

trigger: none

pr: none

parameters:
  - name: version_number
    type: string
    default: 0.0.0


pool: 
      vmImage: windows-latest


jobs:
  - deployment: ContinuousDelivery
    environment: deploy
    strategy:
      runOnce:
        deploy:
          steps:
            - task: PowerShell@2
              displayName: Set Package Version
              inputs:
                targetType: FilePath
                filePath: cicd_version.ps1
                arguments: -version ${{ variables.version_number }}
            - template: cicd_template.yml
            - task: TwineAuthenticate@1
              displayName: Twine Authenticate
              inputs:
                artifactFeed: mssql_dataframe/mssql_dataframe
            - script: |
                $(Build.SourcesDirectory)\env\Scripts\python.exe -m twine upload -r mssql_dataframe --config-file $(PYPIRC_PATH) dist/*.whl
              displayName: Upload Artifact
              condition: ne(${{ variables.version_number }},'0.0.0')
            - script: |
                $(Build.SourcesDirectory)\env\Scripts\python.exe -m twine upload -u $(PYPI_UN) -p $(PYPI_PW) dist/*
              displayName: PyPi Upload
              condition: ne(${{ variables.version_number }},'0.0.0')