# Azure Pipelines Continuous Integration that runs automatically on commit. Creates a build environment before
# calling the core cicd.yml template.
#
# See Also
# --------
# CONTRIBUTING.md CICD Build Pipelines for a general overview of the CICD process
# continuous_integration.py for the core of the CI process
# cicd.yml for the core CICD pipeline template

parameters:
- name: remote_agent
  displayName: Remote Agent (Unselect to Run Local)
  type: boolean
  default: True

jobs:

  # run using Azure DevOps provided virtual machine
  - job: remote
    condition: eq(${{ parameters.remote_agent }}, True)
    displayName: 'CI Pipeline Using Remote Agent'
    # use Windows image for SQL Server Express to be included
    pool:
      vmImage: 'windows-latest'
    steps:
      - template: agent.yml
        parameters:
          remote_agent: ${{ parameters.remote_agent }}
          # LocalDB instance "mssqllocaldb" started.
          # server: '(localdb)\\MSSQLLocalDB'
          # server: localdb\mssqllocaldb
          server: localhost\mssqllocaldb
      - template: cicd.yml
        parameters:
          # server: '(localdb)\\MSSQLLocalDB'
          # server: localdb\mssqllocaldb
          server: localhost\mssqllocaldb

  # run locally on laptop (requires Python and SQL Server Express to be installed)
  - job: local
    condition: eq(${{ parameters.remote_agent }}, False)
    displayName: 'CI Pipeline Using Local Agent'
    # local agent set up as described in CONTRIBUTUTING.md
    pool: 'Local Laptop'
    steps:
      - template: agent.yml
        parameters:
          remote_agent: ${{ parameters.remote_agent }}
          server: localhost\SQLEXPRESS
      - template: cicd.yml
        parameters:
          server: localhost\SQLEXPRESS