# CICD Build Pipeline
# https://docs.microsoft.com/en-us/azure/devops/pipelines/?view=azure-devops
# https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema
# https://docs.microsoft.com/azure/devops/pipelines/languages/python
#
# Remote Execution
# 1 Run pipeline in Azure DevOps with remote_agent option selected
#
# Local Execution
# 1 Open PowerShell
# 2 Start the local Azure DevOps agent if previously configured (if not see Contributing.md > CICD Build Pipelines > Local Azure DevOps)
# 2a cd azure-local-pipeline; .\run.cmd;
# 3 Run pipeline in Azure DevOps with remote_agent option deselected
#
# See Also
# --------
#  Contributing.md > CICD Build Pipelines

parameters:
- name: remote_agent
  displayName: Remote Agent (Unselect to Run Local)
  type: boolean
  default: True