# Azure Pipelines Continuous Deployment that runs automatically after... # TODO document the CD portion
#
# See Also
# --------
# CONTRIBUTING.md CICD Build Pipelines for a general overview of the CICD process
# continuous_integration.py and continuous_integration.yml for the core of the CI process

parameters:
- name: remote_agent
  displayName: Remote Agent (Unselect to Run Local)
  type: boolean
  default: True

stages:
- template: stages/build.yml@YAMLTemplates
  parameters:
    environmentName: Build
    serviceName: ${{ parameters.serviceName}}
- template: stages/env_deploy.yml@YAMLTemplates
  parameters:
    environmentName: Dev
    serviceName: ${{ parameters.serviceName}}