# Azure Pipelines Continuous Integration
#
# See Also
# --------
# CONTRIBUTING.md CICD Build Pipelines for a general overview of the CICD process
# cicd_template.yml for the core of the continuous integration process
# cicd_template.py for the core of the entire CICD process

trigger:
  branches:
    include:
    - main

pr:
  autoCancel: true
  branches:
    include:
    - main

parameters:
  - name: version_number
    type: string
    default: 0.0.0

pool: 
      vmImage: windows-latest


stages:

  - stage: ContinuousIntegration
    jobs:
      - job: ContinuousIntegration
        strategy:
          matrix:
            Python38:
              python.version: '3.8'
            # Python39:
            #   python.version: '3.9'
            # Python10:
            #   python.version: '3.10'
        steps:
          - task: UsePythonVersion@0
            displayName: 'Multiple Python Versions'
            inputs:
              versionSpec: '$(python.version)'
          - task: PowerShell@2
            displayName: Set Package Version
            inputs:
              targetType: FilePath
              filePath: $(Build.SourcesDirectory)\cicd\cicd_version.ps1
              arguments: -version ${{ parameters.version_number }}
          - template: cicd_template.yml